-- =====================================================
-- Compare Active Themes vs JSON File
-- =====================================================
-- 
-- Purpose: Find which themes in JSON are NOT active in database
--          and which active themes are NOT in JSON
--
-- Usage: Run this query in Supabase SQL Editor
-- =====================================================

-- 1. Themes in database (active) but NOT in your JSON file
--    (These are currently shown in app but not in your JSON)
SELECT 
    'In DB but NOT in JSON' as status,
    category,
    name,
    is_available,
    is_featured
FROM themes
WHERE is_available = true
  AND name NOT IN (
    -- Add theme names from your JSON file here
    '90s Disposable Camera',
    '90s Retro Anime',
    'Action Figure Hero',
    'Add Objects to Images',
    'Anime Manga Style',
    'Autumn Harvest Magic',
    'Building Block Character',
    'Candy Cane Cheer',
    'Cartoon Truck',
    'Change Image Perspectives',
    'Chibi Nendoroid Style',
    'Christmas Card Portrait',
    'Christmas Lights Glow',
    'Christmas Magic Sparkle',
    'Classic Roadster',
    'Collectible Figure Style',
    'Comedy Anime',
    'Comic Book Hero',
    'Cozy Autumn Hearth',
    'Cubist Portrait',
    'CV/Portfolio Portrait',
    'Cyberpunk Anime',
    'Dark Anime Aesthetic',
    'Designer Toy Art',
    'Designer-Style ID Photo',
    'Die-Cast Model Style',
    'Faded Summer Memory',
    'Fantasy Anime',
    'Fashion Doll Style',
    'Film Noir',
    'Friendly Bus',
    'Friendly Car Eyes',
    'Frosty Winter Wonderland',
    'Generate Image Series',
    'Gingerbread Delight',
    'Gradient Headshot',
    'Grateful Heart Portrait',
    'Harvest Festival Joy',
    'Historical Photo Restore',
    'Image Upscaler (2x-4x)',
    'Impressionist Painting',
    'Kawaii Chibi Style',
    'LinkedIn Headshot',
    'Lo-Fi Aesthetic',
    'Lowbrow Pop Surrealism',
    'Magical Girl Anime',
    'Makoto Shinkai Style',
    'Medieval Painting',
    'Monster Truck Toon',
    'North Pole Elf Magic',
    'Off-Road Explorer',
    'Passport Photo',
    'Pilgrim Heritage Portrait',
    'Pixel Art Retro',
    'Plush Toy Style',
    'Polaroid Instant',
    'Pop Art Style',
    'Profile Banner Generator',
    'Pumpkin Patch Charm',
    'Put Items on Models',
    'Racing Champion',
    'Rally Racer',
    'Remove Background',
    'Remove Object from Image',
    'Renaissance Portrait',
    'Resume Photo',
    'Retro Magazine Cover',
    'Retro Toy Robot',
    'Romance Anime',
    'Santa''s Workshop Style',
    'Sepia Vintage Portrait',
    'Shonen Action Hero',
    'Slice of Life Anime',
    'Slide Background Maker',
    'Snowy Christmas Eve',
    'Sports Anime Hero',
    'Sports Car Hero',
    'Studio Ghibli Style',
    'Style Transfers on Images',
    'Surreal Dream Art',
    'Thanksgiving Feast Portrait',
    'Thumbnail Generator',
    'Turkey Day Fun',
    'Twitter/X Avatar',
    'Vaporwave Aesthetic',
    'VHS 80s Aesthetic',
    'Vintage Anime Portrait',
    'Vintage Cartoon Car',
    'Vintage Christmas Nostalgia',
    'Vintage Film Photography',
    'Watercolor Anime',
    'Wooden Toy Character',
    'Y2K Cyber Aesthetic',
    'Yellow Animated Family'
  )
ORDER BY category, name;

-- 2. Themes in JSON but NOT active in database
--    (These are in your JSON but hidden in app)
SELECT 
    'In JSON but NOT active in DB' as status,
    NULL as category,
    name,
    NULL as is_available,
    NULL as is_featured
FROM (
    VALUES
    ('90s Disposable Camera'),
    ('90s Retro Anime'),
    ('Action Figure Hero'),
    ('Add Objects to Images'),
    ('Anime Manga Style'),
    ('Autumn Harvest Magic'),
    ('Building Block Character'),
    ('Candy Cane Cheer'),
    ('Cartoon Truck'),
    ('Change Image Perspectives'),
    ('Chibi Nendoroid Style'),
    ('Christmas Card Portrait'),
    ('Christmas Lights Glow'),
    ('Christmas Magic Sparkle'),
    ('Classic Roadster'),
    ('Collectible Figure Style'),
    ('Comedy Anime'),
    ('Comic Book Hero'),
    ('Cozy Autumn Hearth'),
    ('Cubist Portrait'),
    ('CV/Portfolio Portrait'),
    ('Cyberpunk Anime'),
    ('Dark Anime Aesthetic'),
    ('Designer Toy Art'),
    ('Designer-Style ID Photo'),
    ('Die-Cast Model Style'),
    ('Faded Summer Memory'),
    ('Fantasy Anime'),
    ('Fashion Doll Style'),
    ('Film Noir'),
    ('Friendly Bus'),
    ('Friendly Car Eyes'),
    ('Frosty Winter Wonderland'),
    ('Generate Image Series'),
    ('Gingerbread Delight'),
    ('Gradient Headshot'),
    ('Grateful Heart Portrait'),
    ('Harvest Festival Joy'),
    ('Historical Photo Restore'),
    ('Image Upscaler (2x-4x)'),
    ('Impressionist Painting'),
    ('Kawaii Chibi Style'),
    ('LinkedIn Headshot'),
    ('Lo-Fi Aesthetic'),
    ('Lowbrow Pop Surrealism'),
    ('Magical Girl Anime'),
    ('Makoto Shinkai Style'),
    ('Medieval Painting'),
    ('Monster Truck Toon'),
    ('North Pole Elf Magic'),
    ('Off-Road Explorer'),
    ('Passport Photo'),
    ('Pilgrim Heritage Portrait'),
    ('Pixel Art Retro'),
    ('Plush Toy Style'),
    ('Polaroid Instant'),
    ('Pop Art Style'),
    ('Profile Banner Generator'),
    ('Pumpkin Patch Charm'),
    ('Put Items on Models'),
    ('Racing Champion'),
    ('Rally Racer'),
    ('Remove Background'),
    ('Remove Object from Image'),
    ('Renaissance Portrait'),
    ('Resume Photo'),
    ('Retro Magazine Cover'),
    ('Retro Toy Robot'),
    ('Romance Anime'),
    ('Santa''s Workshop Style'),
    ('Sepia Vintage Portrait'),
    ('Shonen Action Hero'),
    ('Slice of Life Anime'),
    ('Slide Background Maker'),
    ('Snowy Christmas Eve'),
    ('Sports Anime Hero'),
    ('Sports Car Hero'),
    ('Studio Ghibli Style'),
    ('Style Transfers on Images'),
    ('Surreal Dream Art'),
    ('Thanksgiving Feast Portrait'),
    ('Thumbnail Generator'),
    ('Turkey Day Fun'),
    ('Twitter/X Avatar'),
    ('Vaporwave Aesthetic'),
    ('VHS 80s Aesthetic'),
    ('Vintage Anime Portrait'),
    ('Vintage Cartoon Car'),
    ('Vintage Christmas Nostalgia'),
    ('Vintage Film Photography'),
    ('Watercolor Anime'),
    ('Wooden Toy Character'),
    ('Y2K Cyber Aesthetic'),
    ('Yellow Animated Family')
) AS json_themes(name)
WHERE name NOT IN (
    SELECT name 
    FROM themes 
    WHERE is_available = true
)
ORDER BY name;
